spring.application.name=app

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate

spring.datasource.url=jdbc:mysql://localhost:3306/libdb
spring.datasource.username=user
spring.datasource.password=secret

# Acutator
management.endpoints.web.exposure.include=info,health
